# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.srcs/sources_1/bd/bd_ab/ip/bd_ab_bd_refbuf_0/bd_ab_bd_refbuf_0.xci
# IP: The module: 'bd_ab_bd_refbuf_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_refbuf_0/bd_ab_bd_refbuf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ab_bd_refbuf_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_refbuf_0/bd_ab_bd_refbuf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ab_bd_refbuf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.srcs/sources_1/bd/bd_ab/ip/bd_ab_bd_refbuf_0/bd_ab_bd_refbuf_0.xci
# IP: The module: 'bd_ab_bd_refbuf_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_refbuf_0/bd_ab_bd_refbuf_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ab_bd_refbuf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_refbuf_0/bd_ab_bd_refbuf_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ab_bd_refbuf_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
