# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/kcu116_generado.xdc

# Block Designs: bd/bd_ab/bd_ab.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ab || ORIG_REF_NAME==bd_ab} -quiet] -quiet

# IP: bd/bd_ab/ip/bd_ab_bd_xdma_0/bd_ab_bd_xdma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0 || ORIG_REF_NAME==bd_ab_bd_xdma_0} -quiet] -quiet

# IP: bd/bd_ab/ip/bd_ab_bd_clk_tx_0/bd_ab_bd_clk_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ab_bd_clk_tx_0 || ORIG_REF_NAME==bd_ab_bd_clk_tx_0} -quiet] -quiet

# IP: bd/bd_ab/ip/bd_ab_bd_ab_top_0/bd_ab_bd_ab_top_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ab_bd_ab_top_0 || ORIG_REF_NAME==bd_ab_bd_ab_top_0} -quiet] -quiet

# IP: bd/bd_ab/ip/bd_ab_bd_refbuf_0/bd_ab_bd_refbuf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ab_bd_refbuf_0 || ORIG_REF_NAME==bd_ab_bd_refbuf_0} -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/bd_ab_ooc.xdc
