# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.srcs/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/bd_ab_bd_xdma_0.xci
# IP: The module: 'bd_ab_bd_xdma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/bd_ab_bd_xdma_0_pcie4_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip} -quiet] -quiet

# IP: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/ip_0/bd_ab_bd_xdma_0_pcie4_ip_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip_gt || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip_gt} -quiet] -quiet

# IP: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_1/xdma_v4_2_0_blk_mem_64_reg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_2_0_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_2_0_blk_mem_64_reg_be} -quiet] -quiet

# IP: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_2/xdma_v4_2_0_blk_mem_64_noreg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_2_0_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_2_0_blk_mem_64_noreg_be} -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/ip_0/synth/bd_ab_bd_xdma_0_pcie4_ip_gt_ooc.xdc

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/ip_0/synth/bd_ab_bd_xdma_0_pcie4_ip_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip_gt || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/bd_ab_bd_xdma_0_pcie4_ip_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/source/ip_pcie4_uscale_plus_impl_x0y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/synth/bd_ab_bd_xdma_0_pcie4_ip_ooc.xdc

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/synth/bd_ab_bd_xdma_0_pcie4_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/source/ip_pcie4_uscale_plus_x0y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_1/xdma_v4_2_0_blk_mem_64_reg_be_ooc.xdc

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_2/xdma_v4_2_0_blk_mem_64_noreg_be_ooc.xdc

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/bd_ab_bd_xdma_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ab_bd_xdma_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/source/bd_ab_bd_xdma_0_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ab_bd_xdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/synth/bd_ab_bd_xdma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ab_bd_xdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.srcs/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/bd_ab_bd_xdma_0.xci
# IP: The module: 'bd_ab_bd_xdma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/bd_ab_bd_xdma_0_pcie4_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip} -quiet] -quiet

# IP: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/ip_0/bd_ab_bd_xdma_0_pcie4_ip_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip_gt || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip_gt} -quiet] -quiet

# IP: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_1/xdma_v4_2_0_blk_mem_64_reg_be.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_2_0_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_2_0_blk_mem_64_reg_be} -quiet] -quiet

# IP: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_2/xdma_v4_2_0_blk_mem_64_noreg_be.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_2_0_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_2_0_blk_mem_64_noreg_be} -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/ip_0/synth/bd_ab_bd_xdma_0_pcie4_ip_gt_ooc.xdc

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/ip_0/synth/bd_ab_bd_xdma_0_pcie4_ip_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip_gt || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/bd_ab_bd_xdma_0_pcie4_ip_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/source/ip_pcie4_uscale_plus_impl_x0y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/synth/bd_ab_bd_xdma_0_pcie4_ip_ooc.xdc

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/synth/bd_ab_bd_xdma_0_pcie4_ip_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_0/source/ip_pcie4_uscale_plus_x0y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_ab_bd_xdma_0_pcie4_ip || ORIG_REF_NAME==bd_ab_bd_xdma_0_pcie4_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_1/xdma_v4_2_0_blk_mem_64_reg_be_ooc.xdc

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/ip_2/xdma_v4_2_0_blk_mem_64_noreg_be_ooc.xdc

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/bd_ab_bd_xdma_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ab_bd_xdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/source/bd_ab_bd_xdma_0_pcie4_uscaleplus_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ab_bd_xdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/nodo_a.gen/sources_1/bd/bd_ab/ip/bd_ab_bd_xdma_0/synth/bd_ab_bd_xdma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ab_bd_xdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
