set_property SRC_FILE_INFO {cfile:c:/Users/diego/Documents/TF-BB84/qkd_abc/vivado/nodo_a/kcu116_generado.xdc rfile:../../../kcu116_generado.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD DIFF_SSTL12} [get_ports sysclk_300_clk_p]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K23 IOSTANDARD DIFF_SSTL12} [get_ports sysclk_300_clk_n]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports pcie_refclk_clk_p]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports pcie_refclk_clk_n]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS18} [get_ports pcie_perstn]
